### ISSUE TITLE
Revisão Sandro Campesatto

### ISSUE THREAD

**Issue by dinhoSilwa** [Projeto-FrontEnd-Fusion/portifolio-colaborativo-codewizard-tigerscode#25]
| Desafio | Nome             | GitHub                                                       | LinkedIn                                                                                     | Data de Início | Data de Entrega | Link do GitHub com o Código                                          | Link do Deploy                                           | Link da Postagem no LinkedIn                                                                                     |
|---------|------------------|--------------------------------------------------------------|----------------------------------------------------------------------------------------------|----------------|-----------------|----------------------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------------------------------------------|
| 01      | Sandro Campesatto | [GitHub](https://github.com/CampesattoJr)                  | [LinkedIn](https://www.linkedin.com/in/campesattojr/)                                       | 04/10/2024     | 13/10/2024      | [Código](https://github.com/CampesattoJr/desafio-fusion-01)         | [Deploy](https://desafio-fusion-01.vercel.app/)           | -                                                                                              |
| 02      | Sandro Campesatto | [GitHub](https://github.com/CampesattoJr)                  | [LinkedIn](https://www.linkedin.com/feed/update/urn:li:share:7253805858302689281/)          | 04/10/2024     | 20/10/2024      | [Código](https://github.com/CampesattoJr/desafio-fusion-02)         | [Deploy](https://desafio-fusion-02.vercel.app/)           | [Postagem](https://www.linkedin.com/feed/update/urn:li:share:7253805858302689281/)              |
| 03      | Sandro Campesatto | [GitHub](https://github.com/CampesattoJr)                  | [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7255381948007673856/)       | 04/10/2024     | 24/10/2024      | [Código](https://github.com/CampesattoJr/desafio-fusion-03)         | [Deploy](https://desafio-fusion-03.vercel.app/)           | [Postagem](https://www.linkedin.com/feed/update/urn:li:activity:7255381948007673856/)            |

**Comment by ruanvictordev** [comment]
## Comentários - Projeto Apresentação Pessoal Frontend

**Estrutura e Organização do Código:**

🙂O projeto está bem estruturado, mas ficam algumas sugestões para melhor organização:

- Separar o arquivo para gerenciamento de rotas (ex: em `/routes/routes.jsx`);
- As seções podem ser divididas em novos componentes para minimizar ainda mais o código; 

**Boas Práticas de Programação:**

O projeto apresentou boas práticas na organização do projeto, tags semanticas, estilização e documentação.

Vale pesquisar sobre: 💡
- Commits Semânticos e Padronização;

**Funcionalidade e Desempenho:**

O projeto atende as funcionalidades exigidas, no caso a apresentação pessoal do desenvolvedor. ✅

É uma page bem leve e pode ser executada em qualquer navegador. 🚀

**Legibilidade e Documentação:**

A documentação está bem escrita. 
Fornece toda a estrutura principal do projeto e demonstra as etapas para execução local. 🧾

😁🤙🏻
Att, [Ruan Victor](https://github.com/ruanvictordev)
Frontend Fusion

**Comment by ruanvictordev** [comment]
## Comentários - Projeto Galeria de Imagens

Objetivos:

- [X] Visualização de imagens obtidas da API [Picsum Photos](https://picsum.photos/v2/list).

- [X] Funcionalidade para salvar imagens nos favoritos. 💾

Objetivos opcionais:

- [ ] Opção de aplicar filtros para visualizar imagens por categoria, cor, etc. 🎨

- [X] Ao clicar em uma imagem, exibir informações detalhadas como autor, dimensões, e qualquer outra propriedade relevante disponível na API. 🖼️

### Estrutura e Organização do Código:

O projeto está bem organizado, possui fácil entendimento. Uma sugestão adicional para organização seria criar um hook em um arquivo para o fetch das fotos vindas da API e chamar em `/Home/index.jsx` 🧱⚙

### Boas Práticas de Programação:

Praticou bem o versionamento de projeto com a padronização de commits e criou uma lógica eficaz para a renderização dos componentes de imagens sem comprometer o carregamento da página.

### Funcionalidade e Desempenho:

As principais funcionalidades exigidas no desafio foram cumpridas, mas as opções de filtro não estão visiveis para o usuário, apenas é possiivel filtrar modificando o projeto internamente. Pode ser uma boa implementação futura. 💪🏻

### Legibilidade e Documentação:

A documentação está bem organizada e descreve bem o projeto. 👏🏻

😁🤙🏻
Att, [Ruan Victor](https://github.com/ruanvictordev)
Frontend Fusion

**Comment by ruanvictordev** [comment]
## Comentários - Projeto Formulário de Cadastro

Objetivos:

- [x] Nome completo (Obrigatório) 🗣️

- [x] E-mail (Obrigatório, com validação de formato) 📧

- [x] Telefone (Obrigatório) 📞

- [x] Cargo pretendido (Obrigatório) 💼


### Estrutura e Organização do Código:

O projeto está bem estruturado, mas ficam algumas sugestões para melhor organização:

- Separar o arquivo para gerenciamento de rotas (ex: em /routes/routes.jsx);

### Boas Práticas de Programação:

Praticou boas praticas para validação de dados e feedback ao usuario impedindo preenchimento incorreto dos campos de input.

### Funcionalidade e Desempenho:

O projeto responde bem e sem atrasos. 🏎

### Legibilidade e Documentação:

A documentação está bem escrita.

😁🤙🏻
Att, [Ruan Victor](https://github.com/ruanvictordev)
Frontend Fusion
